spring.application.name=van-phong-pham

# Ket noi SQL
spring.datasource.url=jdbc:mysql://localhost:3307/QuanLyVanPhongPham?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=123456Luo#

# Cau hinh  JPA/Hibernate
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# 3. chay cong 8080
server.port=8080

#mat khau va user
spring.security.user.name=admin
spring.security.user.password=123456