spring.application.name=van-phong-pham

# 1. Ket noi SQL Server
# Luu y: databaseName phai khop voi ten trong anh la HUIT_Stationery_java
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=HUIT_Stationery_java;encrypt=true;trustServerCertificate=true;
spring.datasource.username=sa
# Thay mat khau duoi day bang mat khau cua tai khoan sa tren may ban
spring.datasource.password=123456Luo#
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver

# 2. Cau hinh JPA/Hibernate
spring.jpa.show-sql=true
# Su dung 'update' de Hibernate tu cap nhat schema neu ban thay doi Entity
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

# 3. Chay cong 8080
server.port=8080

# 4. Cau hinh Security co ban (In-memory)
spring.security.user.name=admin
spring.security.user.password=123456